Changed Colors and Styles
sivaraam/Seminar pull request #1
Opened 2017-04-22 10:47 UTC by harideepan

Changed background colors, radio button styles, Table colors and Submit button style,

2017-04-22 16:39 UTC, sivaraam requested changes
Needs changes. See if you could convert all the `px` values into `em`s. The `em` are a better than pixels as they scale well.

2017-04-22 16:39 UTC, sivaraam commented on css/main.css
> +    transition-duration: 0.4s;
What's the use of the transition-duration ? What are you transforming ?

2017-04-22 16:39 UTC, sivaraam commented on css/main.css
> +    text-decoration: none;
The above two lines don't seem to have any effect, what's their intended use ?

2017-04-22 16:39 UTC, sivaraam commented on css/main.css
> +    width:250px;
That seems too wide. 🤔

2017-04-22 16:54 UTC, harideepan commented on css/main.css
> +    transition-duration: 0.4s;
Actually I changed the color of the button on hover later removed it . For that only I have used transition-duration

2017-04-22 16:56 UTC, harideepan commented on css/main.css
> +    text-decoration: none;
Which two lines?

2017-04-23 03:07 UTC, sivaraam requested changes
There seems to be lots of changes than the title of the Pull request states. Keep changes focused to the title of Pull request. Create new PRs for separate changes. 

You seem to using tabs for indentation. Switch to spaces. See how to make your text editor to insert spaces when you hit tab. The behaviour should be 4spaces for a single tab.

2017-04-23 03:07 UTC, sivaraam commented on css/light-styles.css
> +  border:none;
I remember telling you not to keep anything other than color and font-related rules in this file.

2017-04-23 03:07 UTC, sivaraam commented on css/light-styles.css
> +  border:none;
Same here.

2017-04-23 03:07 UTC, sivaraam commented on css/light-styles.css
> +.zeroPadding
Give a better name than that.

2017-04-23 03:07 UTC, sivaraam commented on css/light-styles.css
> +.zeroPadding
And yes move it to the main.css file

2017-04-23 03:07 UTC, sivaraam commented on css/main.css
> -  transition: border 0.5s linear;
This was there for a reason. Bring it back

2017-04-23 03:07 UTC, sivaraam commented on css/main.css
>    display: none;
Reason for changing the above classes into IDs ?

2017-04-23 03:07 UTC, sivaraam commented on css/main.css
> -/* Hide the status table and book button until the user selects
Don't remove it. Comment it for the mean time.

2017-04-23 03:07 UTC, sivaraam commented on css/main.css
> +    text-decoration: none;
text-align and text-decoration properties

2017-04-23 03:07 UTC, sivaraam commented on css/main.css
> +    margin:0em;
I guess you could remove the margin property. It defaults to 0, I guess.

2017-04-23 03:07 UTC, sivaraam commented on index.html
> +
Add `type` attributes to `link` elements

2017-04-23 03:07 UTC, sivaraam commented on index.html
>                            <option value="20">20 Thu</option>
The default value should be `Select` for a reason. Further don't change the `ID`s and `name` attributes they are meant to be what they are.

2017-04-23 03:07 UTC, sivaraam commented on index.html
>                            <div class="css-button-label-container">
Revert the names to their old values and don't change the name and ID's in the future. _They are meant to be what they are_.

2017-04-23 03:07 UTC, sivaraam commented on index.html
>                            <option value="cse">  CSE </option>
Don't remove comments and do changes as stated before

2017-04-23 03:07 UTC, sivaraam commented on index.html
> -                <div id="status-table-container" class="form-item-container">
Be careful while adding new items. You seemed to have removed the id of the table container. Bring it back.

2017-04-23 03:07 UTC, sivaraam commented on index.html
> -                            </tr>
The `th` elements should be a child of `tr` element

2017-04-23 03:07 UTC, sivaraam commented on index.html
> +							</tr>
Fix the white space issues. They look too odd.

2017-04-23 03:07 UTC, sivaraam commented on index.html
> +							</tr>
White space issues again

2017-04-23 03:07 UTC, sivaraam commented on index.html
>                    <div class="form-item button">
Don't touch the ID's

2017-04-23 03:08 UTC, sivaraam commented
@sirganeshv There seems to be changes in JS files. You better have a look.

2017-04-23 03:11 UTC, sivaraam requested changes

2017-04-23 03:11 UTC, sivaraam commented on css/main.css
> +    width:9.375em;
As stated in previous review. Doesn't that seem too wide.

2017-04-23 03:38 UTC, sivaraam commented
A few things I missed,

1. Change the title and description of this PR to reflect what it changes. In future, create separate PRs for separate changes.
2. Create more commits. Don't try to put every change you do into a single commit. It clutters the purpose of version control
3. The subject selection doesn't look good.
![screenshot from 2017-04-23 08-10-38](https://cloud.githubusercontent.com/assets/12448084/25310555/40664050-27d6-11e7-95bd-1b4cece68e39.png)

2017-04-23 05:03 UTC, sivaraam commented
One more important thing, I remember telling you to give the theme that  **resembles** the one found at the [Sass homepage](http://sass-lang.com/). Change the colors so that they **resemble** the homepage.

2017-04-23 14:52 UTC, closed without merging