Color Changed
sivaraam/Seminar pull request #2
Opened 2017-04-23 08:07 UTC by harideepan

Changed to Light theme
Changed Radio button styles and added style to submit button

2017-04-23 15:00 UTC, sivaraam requested changes
Let the label text of form-items be as it was before.

2017-04-23 15:00 UTC, sivaraam commented on css/main.css
> +  border: none;
Remove the border property.

2017-04-23 15:00 UTC, sivaraam commented on css/light-styles.css
> +	font-family: "source-sans-pro","Helvetica Neue",Helvetica,Arial,sans-serif;
This font choice. Leave that as it was before.
![screenshot from 2017-04-23 20-24-44](https://cloud.githubusercontent.com/assets/12448084/25314515/0f5e07fe-2835-11e7-8f6e-68c964317813.png)
![screenshot from 2017-04-23 20-24-54](https://cloud.githubusercontent.com/assets/12448084/25314517/16d0bac2-2835-11e7-9cf8-83ce09314009.png)

2017-04-23 15:00 UTC, sivaraam commented on css/main.css
> +  border:none;
Don't remove table borders.

2017-04-23 15:00 UTC, sivaraam commented on css/main.css
> +  border:none;
Don't remove this either.

2017-04-23 15:09 UTC, harideepan commented on css/main.css
> +  border:none;
So what shall I do now?
You want the borders to be displayed?

2017-04-24 03:09 UTC, sivaraam commented
Closing in favour of new PR

2017-04-24 03:09 UTC, closed without merging